### ISSUE TITLE
pupu api headers部分新增了 seal 和 sign 

### ISSUE THREAD

**Issue by wozzup** [cddjr/check#3]
看水果蔬菜列表的请求 header头里面有这两个字段

**Comment by cddjr** [comment]
抽空看了一眼，它这个是对请求头的参数做了个校验保护。
破解倒也简单，需要实现魔改MD5、魔改base64，外加一个xxtea。
（这里魔改指的是调整了原算法中的初始常量值或者表格参数）

1、sign是将部分请求头与timestamp、账号信息、签名密钥（"dac032e8fbb9900d840b960429b1a184"）混合后的MD5值
2、seal里面的a值由魔改MD5（sign+“&*()*&”）+8个字节长度的随机值组成，bcd三个也都是8字节长度随机值，f用的是xxtea对称加密算法生成的数据（加密timestamp、账号信息等），但输出的结果是魔改版的base64

目前我这里没有涉及到这些需要被保护的API访问，暂不深入分析了，这里仅作抛砖引玉。
